# Generated by Django 5.2.4 on 2025-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
    ]
